module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Games', [
      {
        user_id: 1,
        killings: 47,
        gold: 430,
        time: 60 * 168 * 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 2,
        killings: 16,
        gold: 277,
        time: 60 * 222 * 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        user_id: 2,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 2,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 2,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        killings: 76,
        gold: 532,
        time: 60 * 141 * 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        killings: 1,
        gold: 30,
        time: 60,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        killings: 1,
        gold: 30,
        time: 60,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        killings: 43,
        gold: 198,
        time: 60 * 187 * 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 5,
        killings: 49,
        gold: 375,
        time: 60 * 268 * 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 5,
        killings: 1,
        gold: 1,
        time: 61,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 5,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 5,
        killings: 1,
        gold: 1,
        time: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 6,
        killings: 3,
        gold: 36,
        time: 60 * 62 * 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Games', null, {});
  },
};
